CREATE TABLE llx_returnmgmt_return(
    rowid                  INTEGER       AUTO_INCREMENT PRIMARY KEY,
    ref                    VARCHAR(30)   NOT NULL,
    entity                 INTEGER       NOT NULL DEFAULT 1,
    fk_soc                 INTEGER       NOT NULL,
    fk_product             INTEGER,
    serial_number          VARCHAR(128),
    return_reason          VARCHAR(50),
    resolution_type        VARCHAR(50),
    fk_warehouse           INTEGER,
    return_tracking        VARCHAR(100),
    date_received          DATETIME,
    date_resolved          DATETIME,
    fk_user_assigned       INTEGER,
    condition_on_receipt   VARCHAR(20),
    refund_amount          DOUBLE(24,8),
    exchange_fk_product    INTEGER,
    exchange_serial_number VARCHAR(128),
    status                 SMALLINT      NOT NULL DEFAULT 0,
    note_private           TEXT,
    note_public            TEXT,
    date_creation          DATETIME      NOT NULL,
    date_validation        DATETIME,
    date_closed            DATETIME,
    tms                    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    fk_user_creat          INTEGER,
    fk_user_valid          INTEGER,
    fk_user_close          INTEGER,
    fk_user_modif          INTEGER,
    import_key             VARCHAR(14),
    model_pdf              VARCHAR(255),
    last_main_doc          VARCHAR(255)
) ENGINE=innodb;
