CREATE TABLE llx_customer_return(
    rowid                  INTEGER       AUTO_INCREMENT PRIMARY KEY,
    ref                    VARCHAR(30)   NOT NULL,
    entity                 INTEGER       NOT NULL DEFAULT 1,
    fk_soc                 INTEGER       NOT NULL,
    fk_commande            INTEGER,
    fk_expedition          INTEGER,
    fk_project             INTEGER,
    fk_warehouse           INTEGER,
    label                  VARCHAR(255),
    return_date            DATETIME,
    status                 SMALLINT      NOT NULL DEFAULT 0,
    note_private           TEXT,
    note_public            TEXT,
    date_creation          DATETIME      NOT NULL,
    date_validation        DATETIME,
    date_closed            DATETIME,
    tms                    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    fk_user_creat          INTEGER,
    fk_user_valid          INTEGER,
    fk_user_close          INTEGER,
    fk_user_modif          INTEGER,
    import_key             VARCHAR(14),
    model_pdf              VARCHAR(255),
    last_main_doc          VARCHAR(255)
) ENGINE=innodb;
